networks:

  nodo:
    external: true

volumes:
  bitcoin-data:
    external: true
  electrs-data:
    external: true

services:

  tor:
    container_name: tor
    image: tor
    restart: always
    volumes:
    networks:
      nodo:
        ipv4_address: 10.0.1.1

  bitcoind:
    container_name: bitcoind
    image: bitcoind
    restart: always
    depends_on:
      - tor
    volumes:
      - bitcoin-data:/root/.bitcoin
    networks:
      nodo:
        ipv4_address: 10.0.1.2

  electrs:
    container_name: electrs
    image: electrs
    restart: always
    volumes:
      - electrs-data:/root/.electrs
    networks:
      nodo:
        ipv4_address: 10.0.1.3


  lnd:
    container_name: lnd
    image: lnd
    restart: always
    volumes:
      - $PWD/.lnd:/root/.lnd
    ports:
      - 10009:10009
    networks:
      nodo:
        ipv4_address: 10.0.1.4

  rtl:
    container_name: rtl
    image: rtl
   # depends_on:
   #   - lnd
    restart: always
    volumes:
      - $PWD/.rtl/RTL:/RTL
      - $PWD/.lnd:/LND
    #  - $PWD/.loop:/LOOP
    networks:
      nodo:
        ipv4_address: 10.0.1.6

  nginx:
    container_name: nginx
    image: nginx


    restart: always
    ports:
      - 50002:50002
      - 4002:4002
      - 443:443
    networks:
      nodo:
        ipv4_address: 10.0.1.10
